// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfiguratorBundle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ConfiguratorBundle.proto</summary>
public static partial class ConfiguratorBundleReflection {

  #region Descriptor
  /// <summary>File descriptor for ConfiguratorBundle.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ConfiguratorBundleReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhDb25maWd1cmF0b3JCdW5kbGUucHJvdG8iZwoSQ29uZmlndXJhdG9yQnVu",
          "ZGxlEg8KB2RhdGFfaW4YASABKAkSEAoIaXNfdmFsaWQYAiABKAgSFQoNZGF0",
          "YV9vdXRfY29zdBgDIAEoCRIXCg9kYXRhX291dF93ZWlnaHQYBCABKAliBnBy",
          "b3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ConfiguratorBundle), global::ConfiguratorBundle.Parser, new[]{ "DataIn", "IsValid", "DataOutCost", "DataOutWeight" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ConfiguratorBundle : pb::IMessage<ConfiguratorBundle>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ConfiguratorBundle> _parser = new pb::MessageParser<ConfiguratorBundle>(() => new ConfiguratorBundle());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ConfiguratorBundle> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfiguratorBundleReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConfiguratorBundle() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConfiguratorBundle(ConfiguratorBundle other) : this() {
    dataIn_ = other.dataIn_;
    isValid_ = other.isValid_;
    dataOutCost_ = other.dataOutCost_;
    dataOutWeight_ = other.dataOutWeight_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConfiguratorBundle Clone() {
    return new ConfiguratorBundle(this);
  }

  /// <summary>Field number for the "data_in" field.</summary>
  public const int DataInFieldNumber = 1;
  private string dataIn_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DataIn {
    get { return dataIn_; }
    set {
      dataIn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_valid" field.</summary>
  public const int IsValidFieldNumber = 2;
  private bool isValid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsValid {
    get { return isValid_; }
    set {
      isValid_ = value;
    }
  }

  /// <summary>Field number for the "data_out_cost" field.</summary>
  public const int DataOutCostFieldNumber = 3;
  private string dataOutCost_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DataOutCost {
    get { return dataOutCost_; }
    set {
      dataOutCost_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "data_out_weight" field.</summary>
  public const int DataOutWeightFieldNumber = 4;
  private string dataOutWeight_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DataOutWeight {
    get { return dataOutWeight_; }
    set {
      dataOutWeight_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ConfiguratorBundle);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ConfiguratorBundle other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DataIn != other.DataIn) return false;
    if (IsValid != other.IsValid) return false;
    if (DataOutCost != other.DataOutCost) return false;
    if (DataOutWeight != other.DataOutWeight) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (DataIn.Length != 0) hash ^= DataIn.GetHashCode();
    if (IsValid != false) hash ^= IsValid.GetHashCode();
    if (DataOutCost.Length != 0) hash ^= DataOutCost.GetHashCode();
    if (DataOutWeight.Length != 0) hash ^= DataOutWeight.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DataIn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DataIn);
    }
    if (IsValid != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsValid);
    }
    if (DataOutCost.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(DataOutCost);
    }
    if (DataOutWeight.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(DataOutWeight);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DataIn.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DataIn);
    }
    if (IsValid != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsValid);
    }
    if (DataOutCost.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(DataOutCost);
    }
    if (DataOutWeight.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(DataOutWeight);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (DataIn.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DataIn);
    }
    if (IsValid != false) {
      size += 1 + 1;
    }
    if (DataOutCost.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DataOutCost);
    }
    if (DataOutWeight.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DataOutWeight);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ConfiguratorBundle other) {
    if (other == null) {
      return;
    }
    if (other.DataIn.Length != 0) {
      DataIn = other.DataIn;
    }
    if (other.IsValid != false) {
      IsValid = other.IsValid;
    }
    if (other.DataOutCost.Length != 0) {
      DataOutCost = other.DataOutCost;
    }
    if (other.DataOutWeight.Length != 0) {
      DataOutWeight = other.DataOutWeight;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DataIn = input.ReadString();
          break;
        }
        case 16: {
          IsValid = input.ReadBool();
          break;
        }
        case 26: {
          DataOutCost = input.ReadString();
          break;
        }
        case 34: {
          DataOutWeight = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DataIn = input.ReadString();
          break;
        }
        case 16: {
          IsValid = input.ReadBool();
          break;
        }
        case 26: {
          DataOutCost = input.ReadString();
          break;
        }
        case 34: {
          DataOutWeight = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
