// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/switch_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto3_2fswitch_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto3_2fswitch_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto3_2fswitch_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto3_2fswitch_5fconfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto3_2fswitch_5fconfig_2eproto;
class SwitchConfig;
struct SwitchConfigDefaultTypeInternal;
extern SwitchConfigDefaultTypeInternal _SwitchConfig_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SwitchConfig* Arena::CreateMaybeMessage<::SwitchConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class SwitchConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SwitchConfig) */ {
 public:
  inline SwitchConfig() : SwitchConfig(nullptr) {}
  ~SwitchConfig() override;
  explicit PROTOBUF_CONSTEXPR SwitchConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SwitchConfig(const SwitchConfig& from);
  SwitchConfig(SwitchConfig&& from) noexcept
    : SwitchConfig() {
    *this = ::std::move(from);
  }

  inline SwitchConfig& operator=(const SwitchConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwitchConfig& operator=(SwitchConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SwitchConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const SwitchConfig* internal_default_instance() {
    return reinterpret_cast<const SwitchConfig*>(
               &_SwitchConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SwitchConfig& a, SwitchConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(SwitchConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwitchConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SwitchConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SwitchConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SwitchConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SwitchConfig& from) {
    SwitchConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwitchConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SwitchConfig";
  }
  protected:
  explicit SwitchConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLearningRateFieldNumber = 1,
    kBatchSizeFieldNumber = 2,
    kEpochsFieldNumber = 3,
    kDpFieldNumber = 4,
    kEpsilonFieldNumber = 5,
  };
  // float learning_rate = 1;
  void clear_learning_rate();
  float learning_rate() const;
  void set_learning_rate(float value);
  private:
  float _internal_learning_rate() const;
  void _internal_set_learning_rate(float value);
  public:

  // int32 batch_size = 2;
  void clear_batch_size();
  int32_t batch_size() const;
  void set_batch_size(int32_t value);
  private:
  int32_t _internal_batch_size() const;
  void _internal_set_batch_size(int32_t value);
  public:

  // int32 epochs = 3;
  void clear_epochs();
  int32_t epochs() const;
  void set_epochs(int32_t value);
  private:
  int32_t _internal_epochs() const;
  void _internal_set_epochs(int32_t value);
  public:

  // bool dp = 4;
  void clear_dp();
  bool dp() const;
  void set_dp(bool value);
  private:
  bool _internal_dp() const;
  void _internal_set_dp(bool value);
  public:

  // float epsilon = 5;
  void clear_epsilon();
  float epsilon() const;
  void set_epsilon(float value);
  private:
  float _internal_epsilon() const;
  void _internal_set_epsilon(float value);
  public:

  // @@protoc_insertion_point(class_scope:SwitchConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float learning_rate_;
    int32_t batch_size_;
    int32_t epochs_;
    bool dp_;
    float epsilon_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto3_2fswitch_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SwitchConfig

// float learning_rate = 1;
inline void SwitchConfig::clear_learning_rate() {
  _impl_.learning_rate_ = 0;
}
inline float SwitchConfig::_internal_learning_rate() const {
  return _impl_.learning_rate_;
}
inline float SwitchConfig::learning_rate() const {
  // @@protoc_insertion_point(field_get:SwitchConfig.learning_rate)
  return _internal_learning_rate();
}
inline void SwitchConfig::_internal_set_learning_rate(float value) {
  
  _impl_.learning_rate_ = value;
}
inline void SwitchConfig::set_learning_rate(float value) {
  _internal_set_learning_rate(value);
  // @@protoc_insertion_point(field_set:SwitchConfig.learning_rate)
}

// int32 batch_size = 2;
inline void SwitchConfig::clear_batch_size() {
  _impl_.batch_size_ = 0;
}
inline int32_t SwitchConfig::_internal_batch_size() const {
  return _impl_.batch_size_;
}
inline int32_t SwitchConfig::batch_size() const {
  // @@protoc_insertion_point(field_get:SwitchConfig.batch_size)
  return _internal_batch_size();
}
inline void SwitchConfig::_internal_set_batch_size(int32_t value) {
  
  _impl_.batch_size_ = value;
}
inline void SwitchConfig::set_batch_size(int32_t value) {
  _internal_set_batch_size(value);
  // @@protoc_insertion_point(field_set:SwitchConfig.batch_size)
}

// int32 epochs = 3;
inline void SwitchConfig::clear_epochs() {
  _impl_.epochs_ = 0;
}
inline int32_t SwitchConfig::_internal_epochs() const {
  return _impl_.epochs_;
}
inline int32_t SwitchConfig::epochs() const {
  // @@protoc_insertion_point(field_get:SwitchConfig.epochs)
  return _internal_epochs();
}
inline void SwitchConfig::_internal_set_epochs(int32_t value) {
  
  _impl_.epochs_ = value;
}
inline void SwitchConfig::set_epochs(int32_t value) {
  _internal_set_epochs(value);
  // @@protoc_insertion_point(field_set:SwitchConfig.epochs)
}

// bool dp = 4;
inline void SwitchConfig::clear_dp() {
  _impl_.dp_ = false;
}
inline bool SwitchConfig::_internal_dp() const {
  return _impl_.dp_;
}
inline bool SwitchConfig::dp() const {
  // @@protoc_insertion_point(field_get:SwitchConfig.dp)
  return _internal_dp();
}
inline void SwitchConfig::_internal_set_dp(bool value) {
  
  _impl_.dp_ = value;
}
inline void SwitchConfig::set_dp(bool value) {
  _internal_set_dp(value);
  // @@protoc_insertion_point(field_set:SwitchConfig.dp)
}

// float epsilon = 5;
inline void SwitchConfig::clear_epsilon() {
  _impl_.epsilon_ = 0;
}
inline float SwitchConfig::_internal_epsilon() const {
  return _impl_.epsilon_;
}
inline float SwitchConfig::epsilon() const {
  // @@protoc_insertion_point(field_get:SwitchConfig.epsilon)
  return _internal_epsilon();
}
inline void SwitchConfig::_internal_set_epsilon(float value) {
  
  _impl_.epsilon_ = value;
}
inline void SwitchConfig::set_epsilon(float value) {
  _internal_set_epsilon(value);
  // @@protoc_insertion_point(field_set:SwitchConfig.epsilon)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto3_2fswitch_5fconfig_2eproto
