# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfiguratorBundle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43onfiguratorBundle.proto\"I\n\x12\x43onfiguratorBundle\x12\x0f\n\x07\x64\x61ta_in\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_out\x18\x02 \x01(\t\x12\x10\n\x08is_valid\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConfiguratorBundle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONFIGURATORBUNDLE']._serialized_start=28
  _globals['_CONFIGURATORBUNDLE']._serialized_end=101
# @@protoc_insertion_point(module_scope)
