<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/agent.proto

namespace GPBMetadata\Proto3;

class Agent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Q
proto3/agent.proto"3
Weights

id (
name (	
weight (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

